// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content: dynamic(() => import("./Content")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  pricing: dynamic(() => import("./Pricing")),
};
